// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Social_Network_asp_net_core.Entities.MyDbContext;

#nullable disable

namespace Social_Network_asp_net_core.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240329030043_addMessage")]
    partial class addMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Social_Network_asp_net_core.Entities.Message", b =>
                {
                    b.Property<long>("id_mes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id_mes"));

                    b.Property<string>("content")
                        .HasColumnType("longtext");

                    b.Property<long>("idReciver")
                        .HasColumnType("bigint");

                    b.Property<long>("idSender")
                        .HasColumnType("bigint");

                    b.Property<int>("messType")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("timestamp"));

                    b.HasKey("id_mes");

                    b.ToTable("message");
                });
#pragma warning restore 612, 618
        }
    }
}
